# Generated by Django 3.1 on 2020-08-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('page_range', models.CharField(max_length=1)),
                ('pages', models.CharField(max_length=6)),
                ('color', models.CharField(max_length=4)),
                ('orientation', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'files',
            },
        ),
    ]
