# Generated by Django 3.1 on 2020-08-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='page_range',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
